# Generated by Django 3.2.21 on 2024-06-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0026_courseoverview_entrance_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='enrollment_allowlist',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='enrollment_blocklist',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='enrollment_allowlist',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='enrollment_blocklist',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
