# Generated by Django 3.2.21 on 2024-06-06 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0043_remove_userprofile_allow_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollmentcelebration',
            name='celebrate_weekly_goal',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CourseEnrollmentUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_email', models.CharField(db_index=True, max_length=255)),
                ('enrolled_tpa_history', models.TextField(null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='student.courseenrollment')),
            ],
        ),
    ]
